### ISSUE TITLE
Choose a GDrive CLI

### ISSUE THREAD

**Issue by SamLau95** [data-8/jupyterhub-k8s#9]

**Comment by jiefugong** [comment]
@SamLau95 

There are two main tools that we can use locally to push, pull, and sync files to Google drive. The first is gDrive: https://github.com/prasmussen/gdrive and the second is drive: https://github.com/odeke-em/drive

Upon initial testing, the former option, gDrive, is easier to use and fully supports the functionality we have established as necessary for our students to manage their files. Based on what I have seen, I would like to suggest we continue integration with gDrive as we pursue these issues further.

Drive, while also works, took much more time to understand and is harder to use. I will document some reasons here as to why I do not think this is the better product: 
1. Some commands are more convoluted
   `drive push -depth 1 head-folders`
   A traversal "depth" is used as a means to push and pull entire directories of folders. It is a concept that in my opinion is more convoluted -- gDrive uses simple directory IDs instead of depths with a name in order to push things.
2. Documentation is less organized and commands are not neatly organized. This makes it harder for us to ramp up and understand the tool compared to gDrive
3. List of known issues: doesn't work on Windows, doesn't allow multiple files with the same name, race condition when remote is being modified while we're trying to update the file. 
4. Requires more installation and setting up dependencies such as Go

**Comment by SamLau95** [comment]
@jiefugong that sounds good to me! I looked at those two options as well but didn't go as in depth as you did. Those reasons are valid IMO.

It sounds like we should use `gdrive`.

**Comment by SamLau95** [comment]
This task is done since we've chosen a CLI.
